name: adl2pydm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.11.0
  - pyepics>=3.2.7
  - pyqtgraph>=0.12.0
  - qtpy>=2.2.0
  - six
  - entrypoints
  - setuptools
  - setuptools_scm
  - versioneer
  - pytest
  - pip
  - pip:
    - PySide6>=6.5.0
